# Generated by Django 3.2 on 2021-04-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '정답', 'verbose_name_plural': '정답들'},
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answer_table',
        ),
    ]
